<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.hazendaz.maven.test</groupId>
    <artifactId>jautodoc-mojo-test</artifactId>
    <version>1.0.0</version>
    <build>
        <plugins>
            <plugin>
                <groupId>com.github.hazendaz.maven</groupId>
                <artifactId>jautodoc-maven-plugin</artifactId>
                <configuration>
                    <commentFields>false</commentFields>
                    <commentMethods>false</commentMethods>
                    <commentPrivate>false</commentPrivate>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
