#
#    Copyright 2011-2021 the original author or authors.
#
#     All rights reserved. This program and the accompanying materials are made available under the terms of the Eclipse
#     Public License v1.0 which accompanies this distribution, and is available at
#
#     https://www.eclipse.org/legal/epl-v10.html.
#

name: Sonatype

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository_owner == 'hazendaz' && ! contains(toJSON(github.event.head_commit.message), '[maven-release-plugin]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: zulu
      - name: Deploy to Sonatype
        run: ./mvnw deploy -DskipTests -B --settings ./.mvn/settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
